services:
  # PHP ve Apache Server Services
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Employee-Management-System
    restart: unless-stopped
    volumes:
      # Project files to the container
      - ./src:/var/www/html
    ports:
      # localhost8082 to container's 80th port
      - "8082:80"
    depends_on:
      - db

  # MySQL database service
  db:
    image: mysql:8.0
    # lravel-6 compatibility with mysql v8 settings - critical.
    command: --default-authentication-plugin=mysql_native_password
    container_name: Employee-Management-System-db
    restart: unless-stopped
    ports:
      # mysql access port
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 22222222
      MYSQL_ROOT_PASSWORD: 22222222
    volumes:
      # keep db data persistent
      - db_data:/var/lib/mysql

# volume name for persistent db data
volumes:
  db_data:
